{% set name = "microsoft-kiota-http" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_http-{{ version }}.tar.gz
  sha256: 2ba3d04a3d1d5d600736eebc1e33533d54d87799ac4fbb92c9cce4a97809af61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - microsoft-kiota-abstractions
    - httpx
    - opentelemetry-api
    - opentelemetry-sdk

test:
  imports:
    - kiota_http
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/http/httpx
  summary: Kiota http request adapter implementation for httpx library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/http/httpx
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/http/httpx/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/64252
    reason: Dependency for msgraph-sdk
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - xylar
